name: v04
description: HeroDex 3000 — version 3
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.2
  get_it: ^8.2.0
  meta: ^1.15.0
  uuid: ^4.4.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6