name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPERHERO_API_TOKEN: ${{ secrets.SUPERHERO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        working-directory: v04

      - name: Run analyzer
        run: dart analyze
        working-directory: v04

      - name: Run tests
        run: dart test
        working-directory: v04
